title: Self-Contained Stylization via Steganographyfor Reverse and Serial Style Transfer
description: project page of our WACV2020 paper "Self-Contained Stylization via Steganographyfor Reverse and Serial Style Transfer".
theme: jekyll-theme-cayman
