title: Self-Contained Stylization via Steganography for Reverse and Serial Style Transfer
description: project page of our WACV2020 paper "Self-Contained Stylization via Steganographyfor Reverse and Serial Style Transfer".
theme: jekyll-theme-cayman
google_analytics: UA-177210251-1
